name: "[TEST] NewsFragments"

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["14.x", "15.x"]

    steps:
      - uses: actions/checkout@v1

      - name: Setup node ${{ matrix.run }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.run }}

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ubuntu-latest-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ubuntu-latest-node-

      - name: Install dependencies
        run: |
          npm ci

      - name: Run lint
        run: |
          npm run lint

      - name: Build & Test
        run: |
          npm run test
