name: "[TEST] NewsFragments"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [20, 22]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.version }}
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ matrix.version }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Run Build & Test
        run: npm test
      - uses: SonarSource/sonarqube-scan-action@v5
        if: ${{ vars.SONAR_ENABLED == 'true'  && matrix.version == '20' }}
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
