name: "[TEST] NewsFragments"

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Setup node 17.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 17.x

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2.1.7
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ubuntu-latest-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ubuntu-latest-node-

      - name: Install dependencies
        run: |
          yarn install

      - name: Run lint
        run: |
          yarn run lint

      - name: Build & Test
        run: |
          yarn run test
