name: "[TEST] NewsFragments"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node 16.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.x

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v3.0.6
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ubuntu-latest-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ubuntu-latest-node-

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Build & Test
        run: yarn test
