name: "[PUBLISH] NewsFragments"

on:
  push:
    tags:
      - "*"

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 17.x
      - run: yarn install
      - run: yarn run lint
      - run: yarn run test
      - id: "publish"
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}

      - if: steps.publish.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.old-version }} => ${{ steps.publish.version }}"

      - if: steps.publish.type == 'none'
        run: |
          echo "Version not changed."
