name: "[PUBLISH] NewsFragments"

on:
  push:
    tags:
      - "*"
permissions:
  contents: write
  packages: read

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm install
      - run: npm run lint
      - run: npm test

      - id: "publish"
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}

      - if: ${{ steps.publish.outputs.type }}
        run: |
          echo "Version changed: ${{ steps.publish.old-version }} => ${{ steps.publish.version }}"

      - name: Get current tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Generate release changelog
        run: ./src/cli/index.js preview -p $RELEASE_VERSION >> release.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release.txt
