name: "[PUBLISH] NewsFragments"

on:
  push:
    tags:
      - "*"

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm install
      - run: npm run lint
      - run: npm test
      - id: "publish"
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}

      - if: steps.publish.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.old-version }} => ${{ steps.publish.version }}"

      - if: steps.publish.type == 'none'
        run: |
          echo "Version not changed."
